/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadoratabla;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Aleso
 */
public class CalculadoraTabla extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraTabla
     */
    public CalculadoraTabla() {
        initComponents();
        inicializarTablas();
    }                                                   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrecios = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        lblNombre2 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnDefinirProductos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnTema = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        spnValor = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora De Ventas");

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Producto", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"
            }
        ));
        jScrollPane2.setViewportView(tblVentas);

        tblPrecios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Costo", "Precio Venta"
            }
        ));
        jScrollPane1.setViewportView(tblPrecios);

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Total Ingresos", "Total Utilidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblResultados);

        lblNombre2.setText("Ingresa la cantidad de filas que se requiere");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnDefinirProductos.setText("Definir");
        btnDefinirProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefinirProductosActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnTema.setText("Tema");
        btnTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemaActionPerformed(evt);
            }
        });

        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 153, 204));
        lblNombre.setText("Calculadora De Ventas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnCalcular)
                                .addGap(18, 18, 18)
                                .addComponent(btnDefinirProductos))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(159, 159, 159)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnLimpiar)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnTema))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnGuardar)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnAbrir))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spnValor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(btnSalir)))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblNombre)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblNombre2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalir)
                            .addComponent(spnValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCalcular)
                            .addComponent(btnDefinirProductos)
                            .addComponent(btnGuardar)
                            .addComponent(btnAbrir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar)
                            .addComponent(btnTema))))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        
        DefaultTableModel modeloVentas = (DefaultTableModel) tblVentas.getModel();
        modeloVentas.setRowCount(0);


        DefaultTableModel modeloPrecios = (DefaultTableModel) tblPrecios.getModel();
        modeloPrecios.setRowCount(0);


        DefaultTableModel modeloResultados = (DefaultTableModel) tblResultados.getModel();
        modeloResultados.setRowCount(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnDefinirProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefinirProductosActionPerformed

        //revisa la cantidad de filas que se quiere
        int cantidad;

        try {
        cantidad = (Integer) (spnValor.getValue());
        if (cantidad < 0) {
            JOptionPane.showMessageDialog(this, "El número debe ser positivo.");
            return;
        }
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Ingrese un número válido.");
        return;
        }
        
        //agrega las filas y si no se ocupan las quita
        DefaultTableModel m1 = (DefaultTableModel) tblVentas.getModel();
        DefaultTableModel m2 = (DefaultTableModel) tblPrecios.getModel();
        DefaultTableModel m3 = (DefaultTableModel) tblResultados.getModel();

        m1.setRowCount(cantidad);
        m2.setRowCount(cantidad);
        m3.setRowCount(cantidad);
    }//GEN-LAST:event_btnDefinirProductosActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        //guarda la informacion que se ingresa
        ((DefaultTableModel) tblVentas.getModel()).fireTableDataChanged();
        ((DefaultTableModel) tblPrecios.getModel()).fireTableDataChanged();
        calcularTotales();
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            //selecciona ubicacion el JFilechooser
            JFileChooser fc = new JFileChooser();
            fc.setDialogTitle("Guardar la informacion de las tablas");

            if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            java.io.File f = fc.getSelectedFile();

            // Si no tiene extensión, agregamos .csv
            if (!f.getName().toLowerCase().endsWith(".csv")) {
            f = new java.io.File(f.getAbsolutePath() + ".csv");
        }
        //guarda toda la infromacion
        try (java.io.PrintWriter pw = new java.io.PrintWriter(f)) {

            JTable[] tablas = {tblVentas, tblPrecios, tblResultados};
            String[] nombres = {"Ventas", "Precios", "Resultados"};

            for (int t = 0; t < tablas.length; t++) {
                DefaultTableModel m = (DefaultTableModel) tablas[t].getModel();

                pw.println("Tabla:" + nombres[t]);

                // Encabezados
                for (int c = 0; c < m.getColumnCount(); c++) {
                    pw.print(m.getColumnName(c));
                    if (c < m.getColumnCount() - 1) pw.print(",");
                }
                pw.println();

                // Datos
                for (int i = 0; i < m.getRowCount(); i++) {
                    for (int c = 0; c < m.getColumnCount(); c++) {
                        Object valor = m.getValueAt(i, c);
                        pw.print(valor != null ? valor.toString() : "");
                        if (c < m.getColumnCount() - 1) pw.print(",");
                    }
                    pw.println();
                }
                pw.println();
            }
        }
        JOptionPane.showMessageDialog(this, "Archivo guardado correctamente en:\n" + f.getAbsolutePath());
        }
        }catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al guardar archivo.");
        e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemaActionPerformed
        // TODO add your handling code here:
    if (btnTema.getText().equals("Oscuro")) {
        // modo oscuro
        getContentPane().setBackground(new java.awt.Color(45, 45, 45));

        JButton[] botones = {btnCalcular, btnGuardar, btnTema, btnLimpiar, btnDefinirProductos, btnAbrir, btnSalir};
    for (JButton b : botones) {
        b.setBackground(new java.awt.Color(70, 70, 70));
        b.setForeground(java.awt.Color.WHITE);
    }

    lblNombre.setForeground(java.awt.Color.WHITE);
    lblNombre2.setForeground(java.awt.Color.WHITE);

    btnTema.setText("Claro");

    } else {
    // modo claro
    getContentPane().setBackground(java.awt.Color.WHITE);

    JButton[] botones = {btnCalcular, btnGuardar, btnTema, btnLimpiar, btnDefinirProductos, btnAbrir, btnSalir};
    for (JButton b : botones) {
        b.setBackground(new java.awt.Color(240, 240, 240));
        b.setForeground(java.awt.Color.BLACK);
    }
    lblNombre.setForeground(java.awt.Color.BLACK);
    lblNombre2.setForeground(java.awt.Color.BLACK);

    btnTema.setText("Oscuro");
    }
    }//GEN-LAST:event_btnTemaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        // TODO add your handling code here:
        try {
    JFileChooser fc = new JFileChooser();
    fc.setDialogTitle("Abrir archivo");

    if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        java.io.File f = fc.getSelectedFile();
        java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(f));

        // Limpiar filas de las tablas
        ((DefaultTableModel) tblVentas.getModel()).setRowCount(0);
        ((DefaultTableModel) tblPrecios.getModel()).setRowCount(0);
        ((DefaultTableModel) tblResultados.getModel()).setRowCount(0);

        JTable tablaActual = null;
        DefaultTableModel modeloActual = null;
        boolean primeraLinea = false;
        String line;

        while ((line = br.readLine()) != null) {
            line = line.trim();
            if (line.isEmpty()) continue;

            if (line.startsWith("Tabla:")) {
                String nombre = line.substring(6);
                switch (nombre) {
                    case "Ventas": tablaActual = tblVentas; break;
                    case "Precios": tablaActual = tblPrecios; break;
                    case "Resultados": tablaActual = tblResultados; break;
                }
                modeloActual = (DefaultTableModel) tablaActual.getModel();
                primeraLinea = true;
            } else if (primeraLinea) {
                // Si la tabla ya tiene columnas no se agrega otra vez
                if (modeloActual.getColumnCount() == 0) {
                    String[] encabezados = line.split(",");
                    for (String e : encabezados) modeloActual.addColumn(e);
                }
                primeraLinea = false;
            } else {
                String[] datos = line.split(",");
                modeloActual.addRow(datos);
            }
        }
        br.close();
        JOptionPane.showMessageDialog(this, "Archivo cargado correctamente.");
    }
    } catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error al abrir archivo.");
    e.printStackTrace();
    }
    }//GEN-LAST:event_btnAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraTabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnDefinirProductos;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTema;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JSpinner spnValor;
    private javax.swing.JTable tblPrecios;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTable tblVentas;
    // End of variables declaration//GEN-END:variables

    private void inicializarTablas() {
        
     String columnasVentas[] = {
        "Producto", "Lunes", "Martes", "Miércoles",
        "Jueves", "Viernes", "Sábado", "Domingo"
    };

    DefaultTableModel modeloVentas = new DefaultTableModel(columnasVentas, 0);
    tblVentas.setModel(modeloVentas);

    String columnasPrecios[] = {
        "Producto", "Costo", "Precio Venta"
    };

    DefaultTableModel modeloPrecios = new DefaultTableModel(columnasPrecios, 0);
    tblPrecios.setModel(modeloPrecios);

    // no deja que edite los valores de la tabla 3
    String columnasResultados[] = {
        "Producto", "Ingresos Totales", "Utilidad Total"
    };

    DefaultTableModel modeloResultados = new DefaultTableModel(columnasResultados, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    tblResultados.setModel(modeloResultados);

    modeloVentas.addTableModelListener(e -> {

        if (e.getColumn() == 0) {

            int row = e.getFirstRow();
            Object prodObj = modeloVentas.getValueAt(row, 0);

            if (prodObj == null) return;

            String producto = prodObj.toString().trim();
            if (producto.isEmpty()) return;

            for (int i = 0; i < modeloPrecios.getRowCount(); i++) {
                Object p2 = modeloPrecios.getValueAt(i, 0);
                if (p2 != null && p2.toString().equalsIgnoreCase(producto)) {
                    return;
                }
            }
            
            for (int i = 0; i < modeloPrecios.getRowCount(); i++) {
                Object p2 = modeloPrecios.getValueAt(i, 0);
                if (p2 == null || p2.toString().trim().isEmpty()) {
                    modeloPrecios.setValueAt(producto, i, 0);
                    return; // rellenó la fila existente → terminar
                }
            }
            modeloPrecios.addRow(new Object[]{ producto, "", "" });
        }}); 
    }

    private void calcularTotales() {
        DefaultTableModel modeloVentas = (DefaultTableModel) tblVentas.getModel();
        DefaultTableModel modeloPrecios = (DefaultTableModel) tblPrecios.getModel();
        DefaultTableModel modeloResultados = (DefaultTableModel) tblResultados.getModel();

        int idxProductoPre = -1;
        int idxCostoPre = -1;
        int idxPrecioPre = -1;
        for (int c = 0; c < modeloPrecios.getColumnCount(); c++) {
            String name = modeloPrecios.getColumnName(c).toLowerCase();
            if (name.contains("producto")) idxProductoPre = c;
            else if (name.contains("costo") || name.contains("compra")) idxCostoPre = c;
            else if (name.contains("precio") || name.contains("venta")) idxPrecioPre = c;
        }
        if (idxProductoPre == -1) idxProductoPre = 0;
        if (idxCostoPre == -1) idxCostoPre = 1;
        if (idxPrecioPre == -1) idxPrecioPre = 2;
    
        if (tblVentas.isEditing()) tblVentas.getCellEditor().stopCellEditing();
        if (tblPrecios.isEditing()) tblPrecios.getCellEditor().stopCellEditing();

        modeloResultados.setRowCount(0); // limpiar la tabla cuando ya no se ocupe

    for (int i = 0; i < modeloVentas.getRowCount(); i++) {
        Object prodObj = modeloVentas.getValueAt(i, 0);
        if (prodObj == null) continue;
        String producto = prodObj.toString().trim();
        if (producto.isEmpty()) continue;

        //revisa que coincida las cantidades
        boolean encontrado = false;
        double costo = 0;
        double precioVenta = 0;
        for (int j = 0; j < modeloPrecios.getRowCount(); j++) {
            Object pObj = modeloPrecios.getValueAt(j, idxProductoPre);
            if (pObj == null) continue;
            String prodPrecio = pObj.toString().trim();
            if (producto.equalsIgnoreCase(prodPrecio)) {
                // deja que ponga las comas como valor
                try {
                    Object costoObj = modeloPrecios.getValueAt(j, idxCostoPre);
                    String sCosto = costoObj == null ? "0" : costoObj.toString().trim().replace(",", ".");
                    costo = sCosto.isEmpty() ? 0 : Double.parseDouble(sCosto);
                } catch (Exception ex) {
                    costo = 0;
                }
                try {
                    Object precioObj = modeloPrecios.getValueAt(j, idxPrecioPre);
                    String sPrecio = precioObj == null ? "0" : precioObj.toString().trim().replace(",", ".");
                    precioVenta = sPrecio.isEmpty() ? 0 : Double.parseDouble(sPrecio);
                } catch (Exception ex) {
                    precioVenta = 0;
                }
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
           //pone ceros si no hay nada que se ingresara
            modeloResultados.addRow(new Object[]{ producto, 0.0, 0.0 });
            continue;
        }

        // Suma todos los valores de la semana
        double totalVendido = 0;
        for (int col = 1; col <= 7 && col < modeloVentas.getColumnCount(); col++) {
            Object val = modeloVentas.getValueAt(i, col);
            if (val == null) continue;
            String s = val.toString().trim();
            if (s.isEmpty()) continue;
            s = s.replace(",", "."); // si ingreso un numero decimal pero pongo coma en vez de punto es valido
            try {
                totalVendido += Double.parseDouble(s);
            } catch (NumberFormatException ex) {
                // no le hace caso si se intenta introducir texto en vez de numero osea cantidad
            }
        }
       
        double ingresoTotal = precioVenta * totalVendido;
        double utilidadTotal = (precioVenta - costo) * totalVendido;
        
        // solo deja dos decimales en vez de mas
        ingresoTotal = Math.round(ingresoTotal * 100.0) / 100.0;
        utilidadTotal = Math.round(utilidadTotal * 100.0) / 100.0;

        modeloResultados.addRow(new Object[]{ producto, ingresoTotal, utilidadTotal });
        }
    }
}