/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoconversor;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Aleso
 */
public class ProyectoConversor extends javax.swing.JFrame {
        private boolean temaOscuro = false;
    /**
     * Creates new form proyectoconversor
     */
    public ProyectoConversor() {
        initComponents();
        cbLongitud.setSelectedIndex(-1);
        cbDestino.setSelectedIndex(-1);

        cbMasa.setSelectedIndex(-1);
        cbDestino2.setSelectedIndex(-1);

        cbTemperatura.setSelectedIndex(-1);
        cbDestino3.setSelectedIndex(-1);

        cbVolumen.setSelectedIndex(-1);
        cbDestino4.setSelectedIndex(-1);
        
        cbTiempo.setSelectedIndex(-1);
        cbDestino5.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblValor = new javax.swing.JLabel();
        lblRes = new javax.swing.JLabel();
        txtValor = new javax.swing.JFormattedTextField();
        txtResultado = new javax.swing.JFormattedTextField();
        cbLongitud = new javax.swing.JComboBox<>();
        cbDestino = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        lblValor2 = new javax.swing.JLabel();
        lblRes2 = new javax.swing.JLabel();
        txtValor2 = new javax.swing.JFormattedTextField();
        txtResultado2 = new javax.swing.JFormattedTextField();
        cbMasa = new javax.swing.JComboBox<>();
        cbDestino2 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        lblRes3 = new javax.swing.JLabel();
        lblValor3 = new javax.swing.JLabel();
        txtValor3 = new javax.swing.JFormattedTextField();
        txtResultado3 = new javax.swing.JFormattedTextField();
        cbTemperatura = new javax.swing.JComboBox<>();
        cbDestino3 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        lblRes4 = new javax.swing.JLabel();
        lblValor4 = new javax.swing.JLabel();
        txtValor4 = new javax.swing.JFormattedTextField();
        txtResultado4 = new javax.swing.JFormattedTextField();
        cbVolumen = new javax.swing.JComboBox<>();
        cbDestino4 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblValor5 = new javax.swing.JLabel();
        lblRes5 = new javax.swing.JLabel();
        txtValor5 = new javax.swing.JFormattedTextField();
        txtResultado5 = new javax.swing.JFormattedTextField();
        cbTiempo = new javax.swing.JComboBox<>();
        cbDestino5 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnConvertir = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnTema = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor");

        lblValor.setText("Ingrese el valor:");

        lblRes.setText("Resultado");

        txtResultado.setEditable(false);
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });

        cbLongitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "metros", "kilometros", "millas", "pulgadas" }));

        cbDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "metros", "kilometros", "millas", "pulgadas" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValor, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(lblRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDestino, 0, 95, Short.MAX_VALUE)
                    .addComponent(cbLongitud, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRes)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Longitud", jPanel2);

        lblValor2.setText("Ingrese el valor:");

        lblRes2.setText("Resultado");

        txtResultado2.setEditable(false);

        cbMasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kilogramos", "libras", "gramos" }));

        cbDestino2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kilogramos", "libras", "gramos" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValor2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblRes2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbDestino2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbMasa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor2)
                    .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRes2)
                        .addComponent(cbDestino2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Masa", jPanel3);

        lblRes3.setText("Resultado");

        lblValor3.setText("Ingrese el valor:");

        txtResultado3.setEditable(false);

        cbTemperatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "celsius", "fahrenheit", "kelvin" }));

        cbDestino3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "celsius", "fahrenheit", "kelvin" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRes3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtResultado3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(txtValor3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(lblValor3, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addGap(175, 175, 175)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbDestino3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbTemperatura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(10, 10, 10)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(txtValor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRes3)
                    .addComponent(txtResultado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblValor3)
                        .addComponent(cbTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(cbDestino3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(82, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Temperatura", jPanel4);

        lblRes4.setText("Resultado");

        lblValor4.setText("Ingrese el valor:");

        txtResultado4.setEditable(false);

        cbVolumen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "litros", "mililitros", "galones", " " }));

        cbDestino4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "litros", "mililitros", "galones" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRes4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtResultado4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(txtValor4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(lblValor4, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addGap(175, 175, 175)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbDestino4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbVolumen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(10, 10, 10)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(txtValor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRes4)
                    .addComponent(txtResultado4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblValor4)
                        .addComponent(cbVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(cbDestino4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(82, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Volumen", jPanel5);

        lblValor5.setText("Ingrese el valor:");

        lblRes5.setText("Resultado");

        txtResultado5.setEditable(false);
        txtResultado5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultado5ActionPerformed(evt);
            }
        });

        cbTiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nanosegundo", "microsegundo", "milisegundo", "segundo", "minuto", "hora" }));

        cbDestino5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nanosegundo", "microsegundo", "milisegundo", "segundo", "minuto", "hora" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValor5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRes5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValor5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResultado5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbTiempo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbDestino5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor5)
                    .addComponent(txtValor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRes5)
                    .addComponent(txtResultado5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDestino5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tiempo", jPanel1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Conversor Universal");

        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnTema.setText("Tema");
        btnTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConvertir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnConvertir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTema)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        txtValor.setText("");
        txtResultado.setText("");
        cbLongitud.setSelectedIndex(-1);
        cbDestino.setSelectedIndex(-1);
        txtValor2.setText("");
        txtResultado2.setText("");
        cbLongitud.setSelectedIndex(-1);
        cbDestino2.setSelectedIndex(-1);
        txtValor3.setText("");
        txtResultado3.setText("");
        cbLongitud.setSelectedIndex(-1);
        cbDestino3.setSelectedIndex(-1);
        txtValor4.setText("");
        txtResultado4.setText("");
        cbLongitud.setSelectedIndex(-1);
        cbDestino4.setSelectedIndex(-1);
        txtValor5.setText("");
        txtResultado5.setText("");
        cbTiempo.setSelectedIndex(-1);
        cbDestino5.setSelectedIndex(-1);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        // TODO add your handling code here:
    int tab = jTabbedPane1.getSelectedIndex();

if (tab == 0) { // Longitud
    double valor;

    if (txtValor.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "El campo está vacío. Ingresa un número antes de convertir.",
            "Campo vacío", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        valor = Double.parseDouble(txtValor.getText());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Solo puedes ingresar números. No se permiten letras.",
            "Valor inválido", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (cbLongitud.getSelectedIndex() < 0 || cbDestino.getSelectedIndex() < 0) {
        JOptionPane.showMessageDialog(this,
            "Selecciona la unidad de origen y destino.",
            "Selección incompleta", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String unidad = cbLongitud.getSelectedItem().toString();
    String destino = cbDestino.getSelectedItem().toString();

    if (unidad.equals(destino)) {
        txtResultado.setText(String.valueOf(valor));
        return;
    }

    double metros = 0;
    if (unidad.equals("metros")) metros = valor;
    else if (unidad.equals("kilometros")) metros = valor * 1000;
    else if (unidad.equals("millas")) metros = valor * 1609.34;
    else if (unidad.equals("pulgadas")) metros = valor * 0.0254;

    double resultado = 0;
    if (destino.equals("metros")) resultado = metros;
    else if (destino.equals("kilometros")) resultado = metros / 1000;
    else if (destino.equals("millas")) resultado = metros / 1609.34;
    else if (destino.equals("pulgadas")) resultado = metros / 0.0254;

    txtResultado.setText(String.valueOf(resultado));
}

if (tab == 1) { // Masa
    double valor;

    if (txtValor2.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Ingresa un valor antes de convertir (masa).",
            "Campo vacío", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        valor = Double.parseDouble(txtValor2.getText());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Solo puedes ingresar números",
            "Valor inválido", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (cbMasa.getSelectedIndex() < 0 || cbDestino2.getSelectedIndex() < 0) {
        JOptionPane.showMessageDialog(this,
            "Selecciona la unidad de origen y destino para masa.",
            "Selección incompleta", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String unidad = cbMasa.getSelectedItem().toString();
    String destino = cbDestino2.getSelectedItem().toString();

    if (unidad.equals(destino)) {
        txtResultado2.setText(String.valueOf(valor));
        return;
    }

    double gramos = 0;
    if (unidad.equals("kilogramos")) gramos = valor * 1000;
    else if (unidad.equals("libras")) gramos = valor * 453.592;
    else if (unidad.equals("gramos")) gramos = valor;

    double resultado = 0;
    if (destino.equals("kilogramos")) resultado = gramos / 1000;
    else if (destino.equals("libras")) resultado = gramos / 453.592;
    else if (destino.equals("gramos")) resultado = gramos;

    txtResultado2.setText(String.valueOf(resultado));
}

if (tab == 2) { // Temperatura
    double valor;

    if (txtValor3.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Ingresa un valor antes de convertir (temperatura).",
            "Campo vacío", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        valor = Double.parseDouble(txtValor3.getText());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Solo puedes ingresar números.",
            "Valor inválido", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (cbTemperatura.getSelectedIndex() < 0 || cbDestino3.getSelectedIndex() < 0) {
        JOptionPane.showMessageDialog(this,
            "Selecciona la unidad de origen y destino para temperatura.",
            "Selección incompleta", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String unidad = cbTemperatura.getSelectedItem().toString();
    String destino = cbDestino3.getSelectedItem().toString();

    double resultado = 0;
    if (unidad.equals(destino)) {
        resultado = valor;
    } else if (unidad.equals("celsius") && destino.equals("fahrenheit")) {
        resultado = (valor * 9/5) + 32;
    } else if (unidad.equals("celsius") && destino.equals("kelvin")) {
        resultado = valor + 273.15;
    } else if (unidad.equals("fahrenheit") && destino.equals("celsius")) {
        resultado = (valor - 32) * 5/9;
    } else if (unidad.equals("fahrenheit") && destino.equals("kelvin")) {
        resultado = (valor - 32) * 5/9 + 273.15;
    } else if (unidad.equals("kelvin") && destino.equals("celsius")) {
        resultado = valor - 273.15;
    } else if (unidad.equals("kelvin") && destino.equals("fahrenheit")) {
        resultado = (valor - 273.15) * 9/5 + 32;
    }

    txtResultado3.setText(String.valueOf(resultado));
    }

    if (tab == 3) { // Volumen
    double valor;

    if (txtValor4.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Ingresa un valor antes de convertir (volumen).",
            "Campo vacío", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        valor = Double.parseDouble(txtValor4.getText());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Solo puedes ingresar números.",
            "Valor inválido", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (cbVolumen.getSelectedIndex() < 0 || cbDestino4.getSelectedIndex() < 0) {
        JOptionPane.showMessageDialog(this,
            "Selecciona la unidad de origen y destino para volumen.",
            "Selección incompleta", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String unidad = cbVolumen.getSelectedItem().toString();
    String destino = cbDestino4.getSelectedItem().toString();

    if (unidad.equals(destino)) {
        txtResultado4.setText(String.valueOf(valor));
        return;
    }

    double ml = 0;
    if (unidad.equals("litros")) ml = valor * 1000;
    else if (unidad.equals("mililitros")) ml = valor;
    else if (unidad.equals("galones")) ml = valor * 3785.41;

    double resultado = 0;
    if (destino.equals("litros")) resultado = ml / 1000;
    else if (destino.equals("mililitros")) resultado = ml;
    else if (destino.equals("galones")) resultado = ml / 3785.41;

    txtResultado4.setText(String.valueOf(resultado));
    }

    if (tab == 4) { // Tiempo
    double valor;

    if (txtValor5.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Ingresa un valor antes de convertir (tiempo).",
            "Campo vacío", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        valor = Double.parseDouble(txtValor5.getText());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Solo puedes ingresar números.",
            "Valor inválido", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (cbTiempo.getSelectedIndex() < 0 || cbDestino5.getSelectedIndex() < 0) {
        JOptionPane.showMessageDialog(this,
            "Selecciona la unidad de origen y destino para tiempo.",
            "Selección incompleta", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String unidad = cbTiempo.getSelectedItem().toString();
    String destino = cbDestino5.getSelectedItem().toString();

    if (unidad.equals(destino)) {
        txtResultado5.setText(String.valueOf(valor));
        return;
    }

    double segundos = 0;
    if (unidad.equals("nanosegundo")) segundos = valor / 1_000_000_000;
    else if (unidad.equals("microsegundo")) segundos = valor / 1_000_000;
    else if (unidad.equals("milisegundo")) segundos = valor / 1_000;
    else if (unidad.equals("segundo")) segundos = valor;
    else if (unidad.equals("minuto")) segundos = valor * 60;
    else if (unidad.equals("hora")) segundos = valor * 3600;

    double resultado = 0;
    if (destino.equals("nanosegundo")) resultado = segundos * 1_000_000_000;
    else if (destino.equals("microsegundo")) resultado = segundos * 1_000_000;
    else if (destino.equals("milisegundo")) resultado = segundos * 1_000;
    else if (destino.equals("segundo")) resultado = segundos;
    else if (destino.equals("minuto")) resultado = segundos / 60;
    else if (destino.equals("hora")) resultado = segundos / 3600;

    txtResultado5.setText(String.valueOf(resultado));

    }
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void btnTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemaActionPerformed
        // TODO add your handling code here:
        toggleTema();
    }//GEN-LAST:event_btnTemaActionPerformed

    private void txtResultado5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultado5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultado5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectoConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ProyectoConversor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTema;
    private javax.swing.JComboBox<String> cbDestino;
    private javax.swing.JComboBox<String> cbDestino2;
    private javax.swing.JComboBox<String> cbDestino3;
    private javax.swing.JComboBox<String> cbDestino4;
    private javax.swing.JComboBox<String> cbDestino5;
    private javax.swing.JComboBox<String> cbLongitud;
    private javax.swing.JComboBox<String> cbMasa;
    private javax.swing.JComboBox<String> cbTemperatura;
    private javax.swing.JComboBox<String> cbTiempo;
    private javax.swing.JComboBox<String> cbVolumen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblRes;
    private javax.swing.JLabel lblRes2;
    private javax.swing.JLabel lblRes3;
    private javax.swing.JLabel lblRes4;
    private javax.swing.JLabel lblRes5;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValor2;
    private javax.swing.JLabel lblValor3;
    private javax.swing.JLabel lblValor4;
    private javax.swing.JLabel lblValor5;
    private javax.swing.JFormattedTextField txtResultado;
    private javax.swing.JFormattedTextField txtResultado2;
    private javax.swing.JFormattedTextField txtResultado3;
    private javax.swing.JFormattedTextField txtResultado4;
    private javax.swing.JFormattedTextField txtResultado5;
    private javax.swing.JFormattedTextField txtValor;
    private javax.swing.JFormattedTextField txtValor2;
    private javax.swing.JFormattedTextField txtValor3;
    private javax.swing.JFormattedTextField txtValor4;
    private javax.swing.JFormattedTextField txtValor5;
    // End of variables declaration//GEN-END:variables

    private void toggleTema() {
    temaOscuro = !temaOscuro;

    Color fondo = temaOscuro ? new Color(30,30,30) : Color.WHITE;
    Color texto = temaOscuro ? Color.WHITE : Color.BLACK;
    Color panel = temaOscuro ? new Color(45,45,45) : UIManager.getColor("Panel.background");

    // Fondo de atras
    getContentPane().setBackground(fondo);

    jTabbedPane1.setBackground(panel);
    jTabbedPane1.setForeground(texto);

    JLabel[] labels = {
        lblValor, lblValor2, lblValor3, lblValor4, lblValor5,
        lblRes, lblRes2, lblRes3, lblRes4, lblRes5
    };
    for (JLabel l : labels) {
        if (l != null) {
            l.setForeground(texto); //texto
            l.setBackground(fondo); // fondo de las etiquetas de ingrese y resultado
            l.setOpaque(true);       // se ocupa para validar el fondo
        }
    }
    JFormattedTextField[] campos = {
        txtValor, txtResultado,
        txtValor2, txtResultado2,
        txtValor3, txtResultado3,
        txtValor4, txtResultado4,
        txtValor5, txtResultado5
    };
    for (JFormattedTextField t : campos) {
        if (t != null) {
            t.setBackground(temaOscuro ? Color.DARK_GRAY : Color.WHITE);
            t.setForeground(texto);
            t.setCaretColor(texto);
        }
    }

    JComboBox[] combos = {
        cbLongitud, cbDestino,
        cbMasa, cbDestino2,
        cbTemperatura, cbDestino3,
        cbVolumen, cbDestino4,
        cbTiempo, cbDestino5
    };
        for (JComboBox c : combos) {
            if (c != null) {
                c.setBackground(temaOscuro ? Color.DARK_GRAY : Color.WHITE);
                c.setForeground(texto);
        }
    }

    JButton[] botones = { btnConvertir, btnSalir, btnLimpiar, btnTema };
        for (JButton b : botones) {
            if (b != null) {
                b.setBackground(temaOscuro ? new Color(70,70,70) : UIManager.getColor("Button.background"));
                b.setForeground(texto);
            }
        }
    }
 }